# Close current pane with Ctrl+w
bind-key -n C-w kill-pane

# Ctrl + Alt + S → new tmux window (tab)
bind-key -n C-M-s new-window -c "#{pane_current_path}"

# Ctrl + Alt + Arrow keys → switch tmux windows (tabs)

bind-key -n C-M-Right next-window
bind-key -n C-M-Left  previous-window

# Optional: jump to first / last tab
bind-key -n C-M-Up    select-window -t :0
bind-key -n C-M-Down  select-window -t :$

